[package]
name = "tokyocabinet-rust"
version = "0.1.0"
authors = ["Kexing Chen <ckxkexing@qq.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.138"

[build-dependencies]
bindgen = "0.63"